### ISSUE TITLE
GPUScout paper

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [caps-tum/GPUscout#3]
Hi,

Is it possible to link the pdf of the paper here on github?  It is not open-source on ACM website.

**Comment by stepanvanecek** [comment]
Hi, apologies for the tardy response. 
I don't plan to link it here on the github page for now but you can find the paper on my personal page at my university: https://www.ce.cit.tum.de/caps/mitarbeiter/stepan-vanecek/  Hope this helps.
